//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateMapping
    {
        public int CandiadteId { get; set; }
        public int ReqId { get; set; }
        public int InterviewId { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Interview Interview { get; set; }
        public virtual Request Request { get; set; }
    }
}
