//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterviewComment
    {
        public int InterviewId { get; set; }
        public string EmpId { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string interviewstatus { get; set; }
    
        public virtual Emp Emp { get; set; }
        public virtual Interview Interview { get; set; }
    }
}
