//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int InterviewId { get; set; }
        public int SkillId { get; set; }
        public int Ratings { get; set; }
    
        public virtual Interview Interview { get; set; }
        public virtual SkillInfo SkillInfo { get; set; }
    }
}
