//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.CandidateMappings = new HashSet<CandidateMapping>();
            this.RequestedSkills = new HashSet<RequestedSkill>();
            this.RequestComments = new HashSet<RequestComment>();
            this.Candidates = new HashSet<Candidate>();
        }
    
        public int ReqId { get; set; }
        public int ProductId { get; set; }
        public int Criticality { get; set; }
        public Nullable<int> CostEstimated { get; set; }
        public Nullable<int> CostActual { get; set; }
        public string RequestType { get; set; }
        public string CreatedByEmpId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string AssignedTo { get; set; }
        public int Vacancies { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> minexperience { get; set; }
        public string mineducation { get; set; }
        public int DepartmentId { get; set; }
        public string ReplacementFor { get; set; }
        public Nullable<int> FromProductId { get; set; }
        public Nullable<int> FromDepartmentId { get; set; }
        public string FromManagerId { get; set; }
        public Nullable<int> jobid { get; set; }
        public Nullable<int> minCostEstimated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateMapping> CandidateMappings { get; set; }
        public virtual Dept Dept { get; set; }
        public virtual JobTitle JobTitle { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestedSkill> RequestedSkills { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestComment> RequestComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidate> Candidates { get; set; }
    }
}
